### ISSUE TITLE
How to change response to the text

### ISSUE THREAD

**Issue by wooilung** [ealeksandrov/NodeAPI#11]
When a token overdue，server response Unauthorized. Can i change the response text? How to modify？thank you

**Comment by ealeksandrov** [comment]
Take a look here: https://github.com/ealeksandrov/NodeAPI/blob/master/libs/auth/auth.js#L67-75

**Comment by wooilung** [comment]
Sorry,the response is 'Unauthorized' not 'Token expired'.

**Comment by ealeksandrov** [comment]
That's default Passport.js behaviour. Here is how it can be customised: http://stackoverflow.com/questions/15711127/express-passport-node-js-error-handling

**Comment by wooilung** [comment]
Thank you very much.The problem is resolved,

**Comment by PLQin** [comment]
see : https://github.com/ealeksandrov/NodeAPI/issues/34
