### ISSUE TITLE
Need help with client id and client secret

### ISSUE THREAD

**Issue by valkyr9991234** [ealeksandrov/NodeAPI#12]
I'm a newbie to this and I have a question.
There is a client collection in database. How/where do I generate the data to store there and how do I manage it ? I made my app to register a new user and the only way I can login is to send the client id and client secret in the request. I don't understand how this works and I can't find something on the internet to help. This keys should be unique, right ? 

It works with demo data from generateData.js but that is just as an example.

**Comment by ealeksandrov** [comment]
http://stackoverflow.com/questions/19615372/client-secret-in-oauth-2-0
> Client id and client secret are used to identify what my app is. But they must be hardcoded if it is a client application.

Client credentials = credentials for an App, not for a user. Usually I keep different client credentials for each major version of my mobile app, so I can easily switch off old compromised versions.

**Comment by valkyr9991234** [comment]
So in practice, I save one document with the client id and client secret in clients collection and than hardcode this credentials in my app and use them in requests when I need them. Am I right ?

**Comment by ealeksandrov** [comment]
Yes, that's right.

**Comment by valkyr9991234** [comment]
Got it, thanks a lot.  #closed
