### ISSUE TITLE
Any way to use this with Facebook Login?

### ISSUE THREAD

**Issue by tarushbali** [ealeksandrov/NodeAPI#16]
Hi,

Thanks a lot! This is the best example for me to understand a RESTful API with tokens.

Just wondering - How would you extend this to include Facebook/Google Login?

Thanks
Tarush

**Comment by andretietz** [comment]
May be this is helping you already:

http://mherman.org/blog/2013/11/10/social-authentication-with-passport-dot-js/#.VknMDt8vfUJ

In the comments someone suggests how to implement this for a REST API.


But I agree, that it would be nice, if that would be in this template application.

**Comment by dbof10** [comment]
Please help me how to integrate this OAuth implementation with Facebook login.

Thanks

**Comment by ealeksandrov** [comment]
I'm not sure that it is smart to add every possible feature in this project - it will be blown too big and people will start copy-pasting it without any idea of how it works.
Much better is to look into different smaller atomic articles/tutorials focused on particular features.
