### ISSUE TITLE
Got errors

### ISSUE THREAD

**Issue by sunfeng90** [ealeksandrov/NodeAPI#20]
When I run bin/www,I got:

1、[Error: Cannot find module '../build/browser_build/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

2、TypeError: Cannot read property 'length' of undefined
    at processResults (/project/Nodejs/node_modules/express/express_project/TheOpenSourceNodeAPI/NodeAPI-master/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)

**Comment by i-am-smirnoff** [comment]
This was discussed here - https://github.com/Automattic/mongoose/issues/2757
Solved by updating of package.json like here https://github.com/strob/vdigests/commit/c36a2539227a900c3fb9b9a556fc326f8c75f1ef

So this is easy fix and should be done here I guess..

**Comment by ealeksandrov** [comment]
Thanks for info! Can you check if it will help and maybe submit pull request?

**Comment by i-am-smirnoff** [comment]
Yes I checked and it helped. I mentioned that the same solution was provide for ussie #17 as well.

**Comment by sunfeng90** [comment]
Thank you! I solved by myself. These days, I puzzed with  the android app to request the API.

**Comment by sunfeng90** [comment]
Do you hava any demo about android request this Node API ? Thx.

**Comment by ealeksandrov** [comment]
Should be resolved now

**Comment by ealeksandrov** [comment]
@sunfeng90 sorry, I don't do any Android dev, but it should work as any generic API. Check requests examples in readme and implement them in Android.

**Comment by sunfeng90** [comment]
Didn't you  use the NodeAPI  in Android APP  or  Web site demo？

And  you don't declare AUTHORIZATION.

**Comment by ealeksandrov** [comment]
I'm not sure what is it about, but in this example authorization header declared as `Authorization:'Bearer PUT_YOUR_TOKEN_HERE'`.

**Comment by sunfeng90** [comment]
Ok,Thanks a lot.
