### ISSUE TITLE
Use a querystring parser for MongoDB

### ISSUE THREAD

**Issue by diegohaz** [ealeksandrov/NodeAPI#21]
I've been working on a simple but powerful library (https://github.com/diegohaz/querymen) to parse querystrings to MongoDB queries. Converting, for example, `/articles?page=2&limit=20` to `{limit: 20, skip: 20}` and other stuff.

I used NodeAPI before and miss this kind of feature. Please, consider adding this or some other library to add this functionality. 😊

**Comment by ealeksandrov** [comment]
Your library looks great, thanks for sharing!
But this example doesn't need to be effective boilerplate of REST APIs, it is just simplest implementation of Node.js + MongoDB API service. The number of possible implementations for routes/queries/access control/etc is infinite.
