### ISSUE TITLE
Socket.io and oauth2

### ISSUE THREAD

**Issue by BilalDev** [ealeksandrov/NodeAPI#23]
Hi,

Great tutorial 👍 

Do you have any suggestions on how to use your implementation of oauth2 with socket.io ?
I saw a lot of passport/socket.io using passport session ([such as this one](http://stackoverflow.com/questions/13095418/how-to-use-passport-with-express-and-socket-io)) but none of them was implemented the way you do.

Thanks !

**Comment by ealeksandrov** [comment]
Sorry, can't help, I never used `socket.io` before.
I'll keep it open in case you or anyone else will implement it and share the solution.

**Comment by ealeksandrov** [comment]
Closing this for now.
Anyone who have ideas/solutions/links about `socket.io` integration - feel free to post here in discussion.
