### ISSUE TITLE
When i hit API, it asks for username and password 

### ISSUE THREAD

**Issue by niograph** [ealeksandrov/NodeAPI#27]
when i hit these api in postman it asks username and password           http://localhost:1337/api/oauth/token grant_type=password client_id=android client_secret=SomeRandomCharsAndNumbers username=myapi password=abc1234

**Comment by ealeksandrov** [comment]
Please look in #3 for Postman usage.

**Comment by niograph** [comment]
1.Same steps I have done but, result is  error not found. 

![4c71af6f-b184-4962-acaa-a7043b1482c7](https://cloud.githubusercontent.com/assets/15102263/20766618/20bc1994-b75d-11e6-9c21-9fc7d6569784.jpg)

2. In Authorization Oauth2.0, on generating token this error occur.

![282c01fa-85d5-48ca-96ed-402f50df68ee](https://cloud.githubusercontent.com/assets/15102263/20766761/b1d4bc74-b75d-11e6-9390-4ff26b53ba6f.jpg)

3. config.json, I have made changes, while making request.

![image](https://cloud.githubusercontent.com/assets/15102263/20766868/10a56528-b75e-11e6-82a3-c4438f9d1d7b.png)

can u pls tell me complete details of Oauth2.0 in postman

**Comment by ealeksandrov** [comment]
Debug it in REPL. I can't really help much more, it depends on your setup, your DB, etc.
Have you ran `node generateData.js`? Have you verified that DB is generated correctly?
