### ISSUE TITLE
how do you log off?

### ISSUE THREAD

**Issue by rontran** [ealeksandrov/NodeAPI#29]
Great example!

How do you log off?  I used this code but it doesn't work.

```
router.post('/logoff', passport.authenticate('bearer', { session: false }),
    function(req, res) {     
        req.logout();
        return res.send({ authenticated: req.isAuthenticated() });
    }
);
```

**Comment by ealeksandrov** [comment]
I don't think we have "log out" implemented in this example.

1. Just delete access token locally.
2. For improved security add protected endpoint where search for issued tokens (access/refresh) and remove them from database.
