### ISSUE TITLE
Question about the security

### ISSUE THREAD

**Issue by Hanzofm** [ealeksandrov/NodeAPI#30]
Hi,

I've tried this implementation and works fine but is a good secure way to implement the Oauth2 authentication nowadays?

Sorry I'm noob on this and I'm looking for a secure way to do this.

Thanks

**Comment by ealeksandrov** [comment]
I can't answer this because I'm not a security specialist, but good plan of actions would be to read OAuth2 specification and stick with it. That's certainly much better than invent some sort of security with your own algorithm :)
