### ISSUE TITLE
Problem with tokens

### ISSUE THREAD

**Issue by tstarkdk** [ealeksandrov/NodeAPI#31]
Hi,

I am having trouble using the tokens created.
I have cloned the repo and have the following issues.

This works fine

```
http POST http://localhost:1337/api/oauth/token grant_type=password client_id=android client_secret=SomeRandomCharsAndNumbers username=myapi password=abc1234

http POST http://localhost:1337/api/oauth/token grant_type=refresh_token client_id=android client_secret=SomeRandomCharsAndNumbers refresh_token=[TOKEN]
```

(above the token is send in the body)

The following gives me an:
```
{
  "error": "Validation error"
}
```
```
http POST http://localhost:1337/api/articles title=NewArticle author='John Doe' description='Lorem ipsum dolar sit amet' images:='[{"kind":"thumbnail", "url":"http://habrahabr.ru/images/write-topic.png"}, {"kind":"detail", "url":"http://habrahabr.ru/images/write-topic.png"}]' Authorization:'Bearer PUT_YOUR_TOKEN_HERE'

http PUT http://localhost:1337/api/articles/YOUR_ARTICLE_ID_HERE title=NewArticleUpdated author='John Doe' description='Lorem ipsum dolar sit amet' images:='[{"kind":"thumbnail", "url":"http://habrahabr.ru/images/write-topic.png"}, {"kind":"detail", "url":"http://habrahabr.ru/images/write-topic.png"}]' Authorization:'Bearer PUT_YOUR_TOKEN_HERE'
```
(here the token is sent in the header) 

I am using postman and have the the post in a x-www-form-urlencoded body and the token ind the header with the Key: "Authorization" and the value: "Bearer fac4e8eeb862fe92c130ac872bd236b91d9d151f563b5f66033cd34e5edc4ea0"

I have also tried without Bearer in front of the token and with the token in the body, and with both the access token and refresh token.

What am I doing wrong?

**Comment by ealeksandrov** [comment]
Have you tried `curl` or `http` directly from terminal?
I don't use Postman, can't say what can be a problem here.

**Comment by yoog568** [comment]
http http://localhost:1337/api/users/info Authorization:'Bearer PUT_YOUR_TOKEN_HERE'

I had get my token,
but I canot get data!!!!

http://127.0.0.1:1337/api?Authorization=%27Bearer+a3bbb3a9ffa2243cc5144d99cb7052b71108d4c7ad7569efbbaf82267c10daef%27

what am i doing wrong?

**Comment by ealeksandrov** [comment]
`Authorization=%27Bearer+a3bbb3a9ffa2243cc5144d99cb7052b71108d4c7ad7569efbbaf82267c10daef%27` - that's not a header, that's URL parameter.

**Comment by yoog568** [comment]
It is ok，I get it.  Thanks
