### ISSUE TITLE
return 401

### ISSUE THREAD

**Issue by CrazyF-wind** [ealeksandrov/NodeAPI#32]
this is my host 
http://localhost:1337/api/oauth/token?grant_type=password&client_id=android&client_secret=SomeRandomCharsAndNumbers123

and username is myapi    
password is abc1234  

but when I post ,return 401,why?

**Comment by CrazyF-wind** [comment]
later,I use the httpie,it can be useful

but I use the postman and httpserver tool return 401

may be this is my fault.And I continue to read it

**Comment by yuttasakcom** [comment]
Body select x-www-form-urlencoded
![screenshot from 2017-05-21 13-24-13](https://cloud.githubusercontent.com/assets/4934943/26281695/74d3193a-3e29-11e7-922c-52debb86b98f.png)

**Comment by CrazyF-wind** [comment]
ok,this time,the postman has been succeed!Thinks!
