### ISSUE TITLE
Request to NodeAPI container timing out

### ISSUE THREAD

**Issue by neelp1** [ealeksandrov/NodeAPI#35]
I used the Docker setup (not the manual setup) as stated in the readme then I used
`http POST http://localhost:1337/api/oauth/token grant_type=password client_id=android client_secret=SomeRandomCharsAndNumbers username=myapi password=abc1234` 
but received
`http: error: Request timed out (30s).`

and also tried using Postman like in here https://github.com/ealeksandrov/NodeAPI/issues/32 but stays on "sending request" status.

Has anyone come across this issue using the Docker setup?

**Comment by yuttasakcom** [comment]
Hey neelp1,
===== Please check step =====
1. git clone https://github.com/ealeksandrov/NodeAPI.git
2. docker-compose up -d --build
3. docker exec nodeapi_node_api_1 node generateData.js
4. postman -> https://documenter.getpostman.com/view/1836801/nodeapi/RW1hhG1N

**Comment by neelp1** [comment]
Still getting the no response. I turned off ssl verification and turned off use my system's proxy. Possibly something wrong with the container? 

![screen shot 2018-05-09 at 3 39 49 pm](https://user-images.githubusercontent.com/8394217/39797430-749257a6-539f-11e8-9cde-78f2ba6d460f.png)

However, images seem ok by looking at the logs:
`{"level":"info","message":"Express server listening on port 1337","timestamp":"2018-05-09T05:05:07.288Z"}
{"level":"error","message":"Connection error: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.19.0.2:27017]","timestamp":"2018-05-09T05:05:07.678Z"}
{"level":"info","message":"Connected to DB!","timestamp":"2018-05-09T05:05:27.957Z"}
{"level":"info","message":"New user - myapi:abc1234","timestamp":"2018-05-09T05:05:28.125Z"}
{"level":"info","message":"New client - android:SomeRandomCharsAndNumbers","timestamp":"2018-05-09T05:05:28.126Z"}`

**Comment by ealeksandrov** [comment]
When I try it with simple commands from README it works fine:

<img width="1410" alt="Screenshot 2019-10-23 at 20 20 04" src="https://user-images.githubusercontent.com/3132438/67417945-8c762100-f5d2-11e9-9a26-4ce35e2ab6b2.png">

Unfortunately I can't help more, since I don't use Docker. At least we can see that the problem is not in package.
