### ISSUE TITLE
Creating a new user

### ISSUE THREAD

**Issue by canb0** [ealeksandrov/NodeAPI#36]
Hello, when I want to create a new user by changing the values in generateData.js file, our initial user is invalidated. New user also does not work.

Which parameters should we change to create more user in the application?

**Comment by ealeksandrov** [comment]
`generateData.js` has line to delete all users, maybe that's why old user is invalidated - https://github.com/ealeksandrov/NodeAPI/blob/master/generateData.js#L14

Changing user and pass there works well for me - https://github.com/ealeksandrov/NodeAPI/blob/master/generateData.js#L16-L17
