### ISSUE TITLE
Make this repository a template repository

### ISSUE THREAD

**Issue by jeremyhalin** [ealeksandrov/NodeAPI#40]
It would be great to be able to use this repo as a template to create a new repo on GitHub.

Do you think this could be a possibility?

[How to create a template repository](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)

**Comment by ealeksandrov** [comment]
Very interesting, thanks for sharing! I'll check it out, but can't promise implementation very soon 🙂

**Comment by ealeksandrov** [comment]
That was actually pretty straightforward, thanks for suggestion! 🙂

<img width="381" alt="image" src="https://user-images.githubusercontent.com/3132438/101474366-20808480-395c-11eb-94ff-deb4ec26d962.png">
