### ISSUE TITLE
`mongodb` vs `sql`

### ISSUE THREAD

**Issue by PLQin** [ealeksandrov/NodeAPI#42]
##### When should I use an `mongodb` ?

**Comment by ealeksandrov** [comment]
This was just an experiment to learn about `NodeJS` and `MongoDB`. I haven't made these choices based on some specific requirements.

For your question I suggest to looks for articles and discussions about "SQL vs NoSQL".

As a general advice I would say that if you don't really need NoSQL features (like dealing with unstructured data) - prefer simple SQL databases.
