### ISSUE TITLE
How to generate clientId and clientSecret for iOS app?

### ISSUE THREAD

**Issue by chenweiyj** [ealeksandrov/NodeAPI#9]
I am an iOS developer. I refer your example to grant the user to be able to access my api. I have register and login apis. However, in register phase, a user only provides username and password. So how can I generate a clientId and clientSecret for my iOS app? Thank you.

**Comment by ShawnStrickland** [comment]
I'm pretty sure you want to generate those manually, as you can see in the dataGen.js; they are just faked data, and are specified to your apps (something that can be controller).  In my instance, I have created one for a webapp with a  client secret and just had to make sure my AngularJS app was sending that along with everything else.  It's another form of validation to makes sure there's no XSS; as a XSS attack is not likely to guess a known client secret and id.

**Comment by ealeksandrov** [comment]
@ShawnStrickland is right.
Also some good insights and best practices you can find on the internet. For example: http://stackoverflow.com/questions/8947437/how-to-generate-oauth-client-identifier-and-client-secret.
